[[books]]
name = "Atomic Habits"
author = "James Clear"

[[classes]]
id = "Other"
name = "Other"

[[classes]]
id = "MATH 172"
name = "Calculus B"

[[classes]]
id = "SWEN 261"
name = "Introduction to Software Engineering"
