[[books]]
name = "Atomic Habits"
author = "James Clear"

[[classes]]
id = "Other"
name = "Other"

[[classes]]
id = "COMM 142"
name = "Introduction Technical Communication"

[[classes]]
id = "CSCI 243"
name = "The Mechanics of Programming"

[[classes]]
id = "MATH 190"
name = "Discrete Mathematics For Computing"

[[classes]]
id = "PHYS 211A"
name = "University Physics 1A"

[[classes]]
id = "UWRT 150"
name = "First Year Writing: Seminar"

[[classes]]
id = "CSCI 99"
name = "Undergraduate Co-op Seminar"
