[package]
name = "fetch"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.54"
dirs = "4.0.0"
fs_extra = "1.2.0"
serde = { version = "1.0.136", features = ["derive"] }
toml = "0.5.8"
chrono = "0.4.19"
task_log = "0.1.4"
